apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-remote
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx
    targetRevision: 9.7.6
    repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    helm:
      values: |-
        service:
          type: ClusterIP
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: remote
  syncPolicy:
    automated:
      prune: true
      selfHeal: true